[project]
name = "simulador-quad"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Christian", email = "cgonzp08@estudiantes.unileon.es" }
]
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.2.3",
    "pandas>=3.0.2",
    "plotly>=6.7.0",
    "pytest>=8.3.4",
    "pyyaml>=6.0.2",
    "scipy>=1.15.2",
]

[project.scripts]
simulador-quad = "simulador_quad.app:main"

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["uv_build>=0.9.20,<0.10.0"]
build-backend = "uv_build"
